### ISSUE TITLE
Repeat interval 

### ISSUE THREAD

**Issue by ilexpl01** [tbowmo/node-red-small-timer#31]
Hi.

Docu says:

Repeat enables the node to repeat status messages with the specified interval (in seconds).

Where do You enter it in node gui ?

![image](https://github.com/tbowmo/node-red-small-timer/assets/67930801/f381818b-e446-4bf8-88fa-d87351ba4e3f)

BR
Mikolaj

**Comment by ilexpl01** [comment]
Updated to 0.15.0 and there it is :)

![image](https://github.com/tbowmo/node-red-small-timer/assets/67930801/a393bc2c-42c7-446f-a62f-1ba5b83fee63)

case closed

**Comment by tbowmo** [comment]
yup.. Documentation always reflects latest version ;) (or at least that's what I'm trying to do)
