### ISSUE TITLE
Memory leak after update ?

### ISSUE THREAD

**Issue by bennybubble** [tbowmo/node-red-small-timer#32]
Hi,

I recently updated from 0.12.0 to 0.15.0 and noticed a slow incrementing memory usage as well as an CPU increase for nodered.
After downgrading to 0.12.0 problem was solved.

Nodered : 3.1.5
RPI4 (openhabian)
node-red-small-timer : 0.15.0

-ben

**Comment by tbowmo** [comment]
Can you give more info? Like how did you use small-timer node? Are there any inputs that control the small-timer node?? How many instances in your flow do you have etc? Also how is it configured?

**Comment by tbowmo** [comment]
@bennybubble I might have an idea. Did you by any chance use "repeat" in one of the instances of small timer? And did you update without editing any of the nodes afterwards?

I have added some new repeat logic that might not get set up properly in 0.15. But haven't seen that it eats memory (Running on an intel platform here).

**Comment by bennybubble** [comment]
Hi

![image](https://github.com/tbowmo/node-red-small-timer/assets/1083428/37eb5472-20ad-476d-b6c5-8ab351b1a008)

This is the node I'm using 3 times in my flows. After upgrading I did not make any changes to it, should I have done so?

-ben

**Comment by tbowmo** [comment]
I'll keep this open until it's validated.

**Comment by bennybubble** [comment]
Hi Thomas,

Let me know if you need help for testing.

-ben

**Comment by tbowmo** [comment]
0.15.1 is on it's way to npmjs, please test with that version.

**Comment by tbowmo** [comment]
@bennybubble did you have a chance to test things out with 0.15.1?

(It's running fine in my setup on intel hardware)

**Comment by bennybubble** [comment]
Yes, just installed 0.15.1 and it seem to work fine, no hughe memory increase anymore!
